### ISSUE TITLE
Intégration de Firebase

### ISSUE THREAD

**Issue by Cyanic76** [Margana314/Amanager#10]
Étant donné que le bot a (ou [est susceptible d'avoir](https://discordapp.com/channels/736689848626446396/736689848626446400/943882895997673562)) des blobs de Google Firebase et que Firebase **est une partie tierce**, il serait mieux, d'en **informer les utilisateurs** sur la [documentation](https://github.com/Margana314/Amanager/wiki) du bot et en faire **une brève phrase** sur le [README](https://github.com/Margana314/Amanager#readme). Il serait tout aussi bien d'ajouter les liens vers les [Terms](https://firebase.google.com/terms), les [Terms de Firebase for Analytics](https://firebase.google.com/terms/analytics) et la [déclaration de confidentialité](https://firebase.google.com/support/privacy) de Google Firebase. @Margana314

**Comment by Margana314** [comment]
y'aura pas firebase/firestore, au final
