### ISSUE TITLE
Rank card

### ISSUE THREAD

**Issue by Cyanic76** [Margana314/Amanager#12]
Bonjour! Cette Issue concerne la demande d'une nouvelle fonctionnalité, d'où le label.

La fonctionnalité, c'est les "cartes de niveaux" (plus connu sous le nom de *rank card* en anglais).

Il s'agirait de:
- [x] dans un premier temps, l'**afficher**,
- [x] personnaliser la couleur de la barre de progression (si possible),
- [x] personnaliser, tout en restant dans des couleurs lisibles, la couleur de fond.

Cette carte contiendrait:
- [x] le nom et l'avatar d'utilisateur,
- [x] le niveau et l'XP (ainsi que l'XP requis pour le niveau suivant),
- [x] la position de l'utilisateur dans le classement,
- [x] une barre de progression, si possible.

Pour les fonds, serait-il possible d'ajouter des **gradients**?

**Comment by Alexiscomete** [comment]
J'entends souvent des personnes être déçu de ne pas connaître leur xp et leur rang car ils ne sont pas top 10, ce serait donc un bon ajout

**Comment by Margana314** [comment]
La commande est implémentée.
