### ISSUE TITLE
BUG sur la commande clear

### ISSUE THREAD

**Issue by Cyanic76** [Margana314/Amanager#17]
J'ai testé la commande `clear` sur des messages qui sont plus vieux que deux semaines, mais le bot n'a pas répondu et ~~a probablement~~ n'a planté (wow).

![Bug](https://user-images.githubusercontent.com/47304192/179951318-11931df4-ac3e-4e0c-8763-b2a6784c3dd4.jpg)

Les messages datent de juin:

![Historique](https://user-images.githubusercontent.com/47304192/179951447-0e745262-7830-41db-8a51-d72066402074.png)

Il faudrait indiquer aux utilisateurs ce problème [lié à Discord](https://wiki.dyno.gg/en/purge-14-day) lors de l'utilisation de cette commande.

**Comment by Margana314** [comment]
Problème réglé : c'est indiqué dans la description de la commande "/clear".
