### ISSUE TITLE
BUG sur la commande help

### ISSUE THREAD

**Issue by Cyanic76** [Margana314/Amanager#18]
La commande `/help` n'est pas fonctionnelle/enregistrée.
Pourtant, elle est mentionnée par ce message.

![C'est rien c'est que discord](https://cdn.discordapp.com/attachments/854342838194929685/1015553845134381066/unknown.png)

**Comment by Cyanic76** [comment]
follow-up; ça serait bien de préciser que la commande [n'existe plus](https://github.com/Margana314/Amanager/wiki/Notes-de-mise-%C3%A0-jour#10-tr-5-novembre-2021)

**Comment by Cyanic76** [comment]
Le bug semble corrigé après test.

**Comment by Margana314** [comment]
bug réglé : /info remplacé dans @Amanager
